name: Test the action
on: create

jobs:
  test:
    name: Test the action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: dump context
        run: echo ${{ toJson(github) }}